# Generated by Django 6.1.1 on 2026-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0002_pricingitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='apporved_by',
            new_name='approved_by',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('site_walk_data', 'Site Walk Data'), ('processing', 'Processing'), ('draft', 'Draft'), ('review', 'Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('sent', 'Sent')], default='site_walk_data', max_length=255),
        ),
    ]
