# Generated by Django 6.1.1 on 2026-09-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0004_add_pricing_item_to_proposallineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
