# Generated by Django 6.1.1 on 2026-09-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai', '0001_initial'),
        ('Proposals', '0003_rename_apporved_by_proposal_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecution',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_executions', to='Proposals.proposal'),
        ),
    ]
