# Generated by Django 6.1.1 on 2026-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai', '0002_aiexecution_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecution',
            name='output_token',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiexecution',
            name='token_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
